export enum Colors {
    PRIMARY_GREEN = '#219653',
    SECONDARY_GREEN = '#CCEBDB',
    PRIMARY_ORANGE = '#ED6F47',
    SECONDARY_ORANGE = '#FBE2DA',
    PRIMARY_TOSCA = '#349EB8',
    SECONDARY_TOSCA = '#d6ecf1',
    PRIMARY_PURPLE = '#495686',
    SECONDARY_PURPLE = '#dbdde7',
    GRAY = '#7D7D7D',
    LINE_STROKE = '#E4E4E4',
    TEXT = '#2E2E2E',
    LIGHT_GRAY = '#F2F3F5',
    DARK_GRAY = '#606060',
    RED = "#ED4747",
    BACKGROUND = "#FAFAFA"
}